apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-flower-class
  namespace: vps-apps
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/max-scale: "2"  # Adjust if you want to allow more than 1 instance
        autoscaling.knative.dev/min-scale: "0"  # Enable scale to zero
        autoscaling.knative.dev/scaleDownDelay: "30s"  # Delay before scaling down
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m5s"
        autoscaling.knative.dev/target: "15"  # Target number of in-flight requests per pod, adjust based on your app's performance characteristics
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/terminationGracePeriodSeconds: "60"
    spec:
      timeoutSeconds: 60
      containers:
      - image: 730335200563.dkr.ecr.ap-south-1.amazonaws.com/vps-apps-flower-class:latest
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.1
            memory: 100Mi
        env:
        - name: PROJECT_ID
          value: "app_id"
        - name: STREAMLIT_PORT
          value: "8080" # Set this to the desired port
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
