apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devpi-hpa
  namespace: vps-tools
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devpi
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

