apiVersion: v1
kind: PersistentVolume
metadata:
  name: devpi-gcs-fuse-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: ""  # Or omit this line entirely
  claimRef:
    namespace: vps-tools
    name: devpi-gcs-fuse-pvc
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: vps-devpi
    readOnly: true
