apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpi-gcs-fuse-pvc
  namespace: vps-tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: devpi-gcs-fuse-pv
