apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpi-pvc
  namespace: vps-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

